const emotes = require("./Discord/emotes.json");
const syntax = require("./Discord/syntax");
const base64 = require("./Extensions/base64");

module.exports = [
    "Loading...",
    "<https://youtu.be/dQw4w9WgXcQ>",
    "<https://youtu.be/dQw4w9WgXcQ>",
    "Click / Space to jump over the spikes",
    base64("Congratulations on decoding this, how do you feel?", 1),
    "Conquering the woof",
    "Hustling towards data",
    `Secret way. ${syntax.emote(emotes.ul.gg)}`,
    "π = 3.14159265358979323846264338327950288419716939937510...",
    "Cute Dash",
    ":m::bed:",
    `${syntax.emote(emotes.icons.dysowolief)} dysowolief`,
    "Watching YouTube is a vacation...",
    `"I can't see anything but it looks great." - RobTop`,
    "Loading is boring, why can't we just skip it?",
    "Alex1304 is probably coding right now...",
    `Sometimes you just have to ${syntax.emote(emotes.icons.shidab)} on them nonwoofers`,
    "#DashGoals",
    "I HAVE A DREAM... that one day we won't have to load",
    "GD Colon is a furry",
    "Does this make my code look big?",
    "Did you know I'm a bot?",
    "Zero divided by zero",
    "Smurffy777",
    "Rob Bert to Pala, come in Rob Bert to Pala",
    `"Don't forget to like and subscribe and comment your favorite woof down below"`,
    "IISuperchatII",
    "WaNnA c0lLaB?",
    "Calculating human intelligence",
    "October react...",
    "Pepper2π probably got tagged today",
    "Initializing triple spikes...",
    "Ardant is small",
    "Life advice: hustle to level 2 while everyone else is distracted at level 1",
    "Don't forget to breathe",
    "The mitochondria is the powerhouse of a cell",
    "The woof is the powerhouse of a woof",
    "Life advice: just because something is morally right, doesn't always make it your best move",
    "sin(x) = x; x = 0",
    `Solving for "x"`,
    "Accelerating towards the mass with great force...",
    "Every sentence is just a different combination of the same 26 letters",
    "Transmiting data... this may take a moment",
    "Real spikes are real",
    "A level will take up less space with unrotated objects",
    "Blasting puns through your computer's Stereo is just Madness",
    "Gettin' these puns Back on Track",
    "Polar coordinates = (rcos(θ), rsin(θ))",
    "Nope, these puns don't Dry Out",
    "Working with logs is just a Base After another Base",
    "Puns are too fun, I Cant Let Go of them",
    "Cubes and robots are Jumpers, did you know that?",
    "You're going to need a Time Machine after reading this",
    "It's like these loading messages are going in Cycles",
    "Increasing the x-position of a move trigger is basically a xSteppin' upwards",
    "Yes, this is Cluttered with puns, just a way to funk things up",
    "There's probably a Theory of Everything",
    "Travel through a circuit and it will technically be an Electroman Adventure",
    "Stepping up to the Club, are ya?",
    "Sadly, these Electrifying puns are not Dynamic",
    "I can tell you your future: I will Force eyes upon a Hexagon",
    "Blasting puns at you is all a part of the Process",
    "I think there's a Theory of Everything, Too",
    "Dominating the Geometrics with puns",
    "Your eyes are Locked Dead on this pun",
    "Where is your Finger on the Big Bang Theory?",
    "WHAT DID YOU DO WITH SPARKY?!?!?!"
];